### ISSUE TITLE
Duvida com relação a paginação de dados resultantes de uma busca

### ISSUE THREAD

**Issue by tghelere** [vuejs-br/forum#19]
Fala galera, blz?
To com um probleminha aqui, com a paginação dos dados vindos de uma api quando filtro em um input de busca.

Estou usando Laravel resource com pagination. 
![post-controller](https://user-images.githubusercontent.com/5022782/40935158-97253f54-680d-11e8-9527-2abb80c085c4.png)

Esta é a estrutura retornada pela api:
![api posts](https://user-images.githubusercontent.com/5022782/40935218-c2f2c264-680d-11e8-89dd-5f11a24a5ba9.png)

E pra fazer a paginação do lado vue estou usando o [gilbitron/laravel-vue-pagination](https://github.com/gilbitron/laravel-vue-pagination)
Este é meu componente vue: [Gist - BlogAllPostsComponent.vue](https://gist.github.com/tghelere/03d089f69f45ec305e6588212be23c44)

### Pagina 1
![blog1](https://user-images.githubusercontent.com/5022782/40935240-d637a48e-680d-11e8-8cf4-88a12eb6e0de.png)
---

### Pagina 2
![blog2](https://user-images.githubusercontent.com/5022782/40935241-d663e8be-680d-11e8-9257-c63caa630c6b.png)
---

### Pagina 3
![blog3](https://user-images.githubusercontent.com/5022782/40935242-d68d39bc-680d-11e8-873a-247b92f76dbc.png)

Eu até entendo onde está o problema, o _filteredItems_ pega o array de posts do abjeto _data_, já o objeto _meta_, que o pagination usa, está um nível acima. A questão é que não tô sabendo como corrigir isso

**Comment by wilcorrea** [comment]
Opa, por que não usar `<pagination class="" :data="filteredItems" :limit="1" @pagination-change-page="getAllPosts"></pagination>`?

**Comment by tghelere** [comment]
Foi a primeira opção que tentei, mas o _filteredItems_ não possui o objeto _meta_. 
O objeto _meta_ está no mesmo nível do array _data_, que é conteúdo do _filteredItems_

**Comment by wilcorrea** [comment]
E por que você precisa do **meta** no **filteredItems**? O componente pagination recebe isso na prop data?

**Comment by tghelere** [comment]
Veja a segunda imagem do meu post inicial. O meta (provido pelo pagination do laravel) contem as informações necessárias para o vue pagination funcionar, já o data, é obviamente os dados a serem paginados. 
```javascript
{
    "data": [{
        "id": 1,
        "title": "Est nostrum consequatur incidunt.",
        "description": "Illum odit omnis qui qui iste corporis. Qui ut voluptatem animi.",
        "body": "Quo aut a blanditiis. Temporibus asperiores tempore fugiat ipsam.",
        "image": "/img/blog/posts/1.jpg",
        "slug": "est-nostrum-consequatur-incidunt",
        "created_at": "2018-06-03 22:14:12",
        "updated_at": "2018-06-03 22:14:12"
    }, ],
    "links": {},
    "meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 10,
        "path": "http://site.com.br/api/posts",
        "per_page": 6,
        "to": 6,
        "total": 60
    }
}
```

```javascript
computed: {
            filteredItems() {
                return this.allPosts.data.filter(post => {
                    return post.title.toLowerCase().indexOf(this.search.toLowerCase()) > -1
                })
            }
        },
```
quando eu passo o allPosts.data,  o meta está no mesmo nível deste data;
A duvida acho que é mais quanto a js do que vue.

**Comment by wilcorrea** [comment]
Acho que agora eu entendi seu problema. Vamos lá.

O componente de paginação que você está usando **não** gerencia os registros, ele apenas usa a entrada do _meta do paginate do eloquent_ para exibir os nós. Só que você faz um filtro **local** e obviamente **invalida** o _meta_ original.

Você tem **duas** opções, _enviar essa query para o laravel_ e mandar ele filtrar isso lá aplicando um where ao title ou _recalcular o meta usando o filteredItems como base_.

Não sei como você manipula o **allPosts** então não tenho como dar dicas sobre a primeira opção.
Optando pela segunda opção você poderia fazer algo como:
```javascript
...
data: () => ({
  meta: {
    current_page: 1,
    from: 1,
    last_page: 1,
    path: '',
    per_page: 6,
    to: 6,
    total: 0
  }
}),
methods: {
  updateMeta (items) {
    this.meta.current_page = 1
    this.meta.last_page = Math.ceil(items.length / this.meta.per_page)
    this.meta.total = items.length
    ...
  }
},
watch: {
  filteredItems (items) {
    this.updateMeta(items)
  }
}
...
```

**Comment by tghelere** [comment]
Fala Will, blz?
Cara, tentei de varias maneiras e não tava conseguindo, deixei isso de lado e fui fazer outras coisas que estava precisando, por exemplo o administrativo.
Tanto o blog publico, quanto o administrativo consomem a mesma api com os posts, e acabei optando por não usar o paginate do laravel, pois estava tendo que criar varias rotas na minha api e não tava dando muito certo.
Este blog não terá muitos posts, então estou trazendo todos os posts de uma vez (atualmente posts fake).
Consegui trabalhar com paginação numa boa no administrativo, lá os posts são exibidos em forma de datatable.
![blog posts admincentrallimp](https://user-images.githubusercontent.com/5022782/41821658-83d8f85c-77ba-11e8-8be6-f4995fc51ff3.png)

Estou usando o bootstrap-vue, e ainda estou tendo dificuldade em paginar o blog publico. 
Dei uma limpada no [código](https://gist.github.com/tghelere/8bf3e98fc4c208fedf568149c4e32035) para ficar fácil entender (tirei a busca pra facilitar, precisarei dela mais tarde).
![captura de tela de 2018-06-24 14-31-29](https://user-images.githubusercontent.com/5022782/41821757-66671e06-77bb-11e8-8f77-04d0d499d2d3.png)

Se puder dar uma olhada no meu [código](https://gist.github.com/tghelere/8bf3e98fc4c208fedf568149c4e32035), acho que devo passar alguma prop pro v-for, mas não to sabendo qual nem como.
Outra dúvida é, devo usar o [Pagination](https://bootstrap-vue.js.org/docs/components/pagination/) ou o [Pagination Navigation](https://bootstrap-vue.js.org/docs/components/pagination-nav/)

**Comment by wilcorrea** [comment]
Qual problema você tá tendo agora @tghelere ?

**Comment by tghelere** [comment]
Basicamente o que tentei explicar na minha ultima resposta. Não consigo paginar os dados de um array usando um v-for, já com datatables foi tranquilinho. Usando bootstrap-vue.
