### ISSUE TITLE
Novo Vuex para Vue.extends

### ISSUE THREAD

**Issue by hernandes** [vuejs-br/forum#28]
Estou com um problema que não acho uma solução agradavel para resolve-lo.

Preciso renderizar um component manualmente porém com uma nova instância do Vuex sem compartilhar com a instância principal do Vue. Segue imagem pra ilustrar:

![image](https://user-images.githubusercontent.com/415107/52967953-82888800-338a-11e9-93d8-685f58959355.png)

Já tentei de varias maneiras (Nova instancia do Vuex, clone do store e por ai vai), porém todas utilizam a mesma referência do VueX, assim duplicado os commit :(

**Comment by IgorHalfeld** [comment]
Hmmm... mas você esta pegando diretamente do `this` é normal o comportamento de pegar a mesma instância, já tentou instânciar outro vuex (criar outra store)?

**Comment by hernandes** [comment]
@IgorHalfeld já tentei utilizar uma nova versão do mesmos porém sem sucesso :(

`import storeData from './store-data'
...

const store = new Vuex.Store(storeData)`

Mesmo assim, os commit nessa nova store, tbm reflete na store principal.

**Comment by VitorLuizC** [comment]
Creio que o Vuex não permita a criação de mais de uma instância porque isso fere o princípio de _single source of truth_.

**Comment by hernandes** [comment]
@VitorLuizC 

Foi o que imaginei quando entrei nesse problema, deixa eu tentar explicar melhor como que funciona a app pra ver se vocês tem um norte pra me orientar heheh.

A aplicação é toda montada por JSON, tanto as telas, campos, metodos e tudo, o problema chega quando uma tela de View tem uma POS DISPLAY (assim que chamamos o mestre-detalhes) com a Listagem de pedido de um cliente por exemplo, porém essa tela é reaproveitada dos components e instanciada dinamicamente como a imagem acima, tem uma versão da aplicação funcionando porém sem o Vuex, mas para melhorar o fluxo dos dados decidi adiciona-ló, assim entrei nesse beco :(

Algumas imagens pra ilustar.

![image](https://user-images.githubusercontent.com/415107/53023191-7c9eaf80-343b-11e9-8e95-ef3e05e443b1.png)

![image](https://user-images.githubusercontent.com/415107/53023263-9b9d4180-343b-11e9-9936-02f94fb9b071.png)

![image](https://user-images.githubusercontent.com/415107/53023278-a8ba3080-343b-11e9-9f60-186767e99645.png)

![image](https://user-images.githubusercontent.com/415107/53023384-df904680-343b-11e9-9884-54bf2dbf4e70.png)

**Comment by VitorLuizC** [comment]
O que você pode fazer é usar uma coleção ou dicionário no Vuex para servir de namespace para cada um dos seus displays. Daí seu display vai usar um índice/namespace para acessar os dados dele no Vuex e realizar as ações.

Isso vai deixar sua store mais complexa, mas você fica alinhado com o princípio do Vuex que é ter uma única fonte de verdade e vai ter controle sobre seus displays como mais um estado do Vuex.
