### ISSUE TITLE
Single Page Application

### ISSUE THREAD

**Issue by tonnon** [vuejs-br/forum#30]
Boa noite, pessoal! Estou desenvolvendo um site com todo o meu portfólio e decidi usar o Vue para uma Single Page Application. Mas estou tendo um erro de script. Na página onde tem todo o portfólio, eu coloquei um filtro gallery, mas ele só está funcionado quando dá um F5 na página. Quando troco de página e volto, ele para de funcionar. O console está limpinho, sem nenhum erro. Vou deixar o link do fiddle, para ter uma noção mais ou menos do código. Obrigado!

https://jsfiddle.net/90rz6act/1/?fbclid=IwAR13FcBuzMh1WhzVJomRKcHsNV-3DMygfe5Ctiz1A5bNHtmu7LBuIzuxrRQ#&togetherjs=j3dm4Jq7Qj

**Comment by soujhony** [comment]
@tonnon aqui funcionou certinho, verifique se não é cache do navegador... ou algum script quebrado específico no seu projeto. Isso de vez em quando acontece aqui na minha máquina, mas é sempre um dos motivos acima citados.. diminuiu bastante quando parei de usar windows para desenvolver, não sei se é este o seu caso ;-)

**Comment by wilcorrea** [comment]
Vou fechar a issue, qualquer coisa a gente reabre
