### ISSUE TITLE
Form dinamico

### ISSUE THREAD

**Issue by Scorpios31** [vuejs-br/forum#31]
Bom dia, antes de mais comecei a poucos dias a desenvolver em Vuejs, portanto se for uma duvida muito ruim, peço desculpa :)

Estou a tentar criar um form dinamico, ou seja, mediante as props enviadas faço a construção do mesmo.
O meu problema é com o campo select que quero enviar uma lista vinda da base de dados.
Do componente pai envio um array fieldsBoosted e dentro dele no campo select em options tem o resultado que vem da base de dados: this.CreatedPromotions.
Mas está sempre vazio no componente filho.
É um pouco confuso mas é dificil explicar. Peço desculpa.

Componente pai

![image](https://user-images.githubusercontent.com/36417392/55072490-2a2c6080-5083-11e9-9a35-d0a9af374619.png)

![image](https://user-images.githubusercontent.com/36417392/55072572-6364d080-5083-11e9-826f-c796d52f17da.png)

![image](https://user-images.githubusercontent.com/36417392/55072688-a626a880-5083-11e9-969a-aac5735d2d22.png)

Componente form

![image](https://user-images.githubusercontent.com/36417392/55072593-7081bf80-5083-11e9-89bd-28046e1e9f76.png)

![image](https://user-images.githubusercontent.com/36417392/55072611-7aa3be00-5083-11e9-86a8-ed77dd1988b1.png)

**Comment by wilcorrea** [comment]
O código ficou ilegível, consegue colocar ele num jsfiddle ou gist?

**Comment by Scorpios31** [comment]
> O código ficou ilegível, consegue colocar ele num jsfiddle ou gist?

Olá wilcorrea, obrigado desde já, coloquei imagens espero que ajude.

**Comment by wilcorrea** [comment]
Como você inicializa o `CreatedPromotions`?

**Comment by Scorpios31** [comment]
No componente pai no ciclo created faço uma chamada em axios para ir buscar os dados a BD.
 

![image](https://user-images.githubusercontent.com/36417392/55073544-e6872600-5085-11e9-931c-0ee138b509b1.png)

 
![image](https://user-images.githubusercontent.com/36417392/55073506-cfe0cf00-5085-11e9-9ae3-52e68b31182f.png)

**Comment by wilcorrea** [comment]
Certo, mas o que você recebe é um array ou objeto? Você já usou o método
$set do Vue? Seria interessante tentar inicializar a propriedade no data
com [] se for um array e tentar usar this.$set pra atualizar o valor dela,
haja visto que você está num contexto complexo. Recomendo dar uma olhada no
vue-formly pra te servir de guia nesse tipo de composição

**Comment by Scorpios31** [comment]
Isto é o que recebo.

![image](https://user-images.githubusercontent.com/36417392/55074459-4088eb00-5088-11e9-8c7c-5ec94574472e.png)

Mais uma vez muito obrigado pela rápida resposta, vou ler então um pouco sobre o $set e vue-formly.

**Comment by wilcorrea** [comment]
Veja se dá certo e volta pra dar um parecer. Forms dinâmicos são desafiadores em vários aspectos. Fazer um componente ser renderizado dinamicamente não é um grande desafio, o desafio é orquestrar tudo ao redor dele dinamicamente.
Atualmente eu parto do princípio que um componente de form que imprime os componentes precisa receber também os hooks dos ciclos de vida, mas para não lotar ele de props eu declaro os hooks numa estrutura que representa os dados do formulário e depois eu passo para ele schema, hooks e tudo o mais que ele abstrair.

Neste artigo eu falo sobre componentes dinâmicos
https://phpzm.rocks/vue-js-componentes-dinamicos-faf195a0b26c

E neste projeto eu implemento do jeito que mais tenho usado atualmente
https://github.com/xprototype/skeleton-quasar

**Comment by Scorpios31** [comment]
Muito Obrigado mesmo, vou ver e estudar um pouco os seus artigos, assim que tiver novidades venho cá novamente agradecer a ajuda :)

**Comment by Scorpios31** [comment]
Olá @wilcorrea , tudo bem?

Desculpe estar a chatear, mas será que poderias me ajudar a perceber uma situação.
Estive a investigar e depois de desanimar consegui chegar a uma solução com o set que sugeriu.

Mas agora tenho outro problema :)

 this.$set(this.fieldsBoosted[0].options, 4, this.fieldsBoosted[0].options.push(...this.CreatedPromotions))

Estou usar esta linha de código, ou seja tenho um array vazio "this.fieldsBoosted[0].options" e estou a substituir o mesmo pelo array ".this.CreatedPromotions", o problema é que ele retorna isto

![image](https://user-images.githubusercontent.com/36417392/55152100-9375a780-5147-11e9-9585-3befeaee4611.png)

mas quando vejo o que chega a essa linha de código é o seguinte 

[ "Bet friday", "teste1", "teste2", null, 3 ]

Não percebo de onde vem esse null e o 3.

Obrigado
