### ISSUE TITLE
TRs fora da Tabela

### ISSUE THREAD

**Issue by fkrul** [vuejs-br/forum#32]
Alguém pode me auxiliar, tenho uma tabela, que dentro tem um componente, as TRs está sendo jogada para fora da tabela, o codigo está aqui [https://jsfiddle.net/fkrul/2hLgq46v/2/]

**Comment by cmpsleo** [comment]
Caso ainda nāo tenha achado uma soluçāo (após um tempo hehe) invés de chamar direto o componente use o atributo `is` chamando o seu component, como a seguir: `<tr is="listuser" v-for="u in listagem" v-bind:usuario="u" />`

Está na documentaçāo falando sobre isso: [DOM Template Parsing Caveats](https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats)
