### ISSUE TITLE
Página Vue recebendo um Post de outro sistema

### ISSUE THREAD

**Issue by marcions** [vuejs-br/forum#34]
Boa tarde pessoal,

Estou implementando um projeto do VueJS integrado com o Bitrix24 CRM. O projeto já está funcionando dentro do Bitrix24 mas estou com um problema. O Bitrix24 manda uma requisição via POST para a minha página de autenticação do Vue com os dados do usuário logado, mas não estou conseguindo acessar esses dados do POST. Ao fazer testes via Postman apresenta o erro CANNOT POST /auth, onde /auth é a minha página de autenticação.

Alguém sabe como habilitar o Vue para receber POST e como faço para pegar esse POST? 

Fiz um teste com PHP usando o var_dump($_POST) e funcionou. Com o Vue não consigo.

Obrigado!!!!

**Comment by kavalcante** [comment]
Acredito que isso não seja possível. Se você utilizasse Nuxt com express ou algo do gênero, você conseguiria criar uma rota para isso.

Nesse cenário, acho que o mais fácil é criar uma aplicação Node simples com express que recebe esse POST, salva esses dados em cookies e te redireciona para a sua aplicação Vue.

Na sua aplicação Vue, você consome esse cookie e autentica o usuário corretamente.

**Comment by AdalgisioAlves** [comment]
Cara, com vue-router acho que você consegue obter estes parâmetros, eu já fiz via GET usando o v-router 

https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation

**Comment by wilcorrea** [comment]
@marcions vou fechar a issue porque as respostas já explicam seu ponto, qualquer coisa você abre de novo.
