### ISSUE TITLE
Alterações na DOM

### ISSUE THREAD

**Issue by csrmds** [vuejs-br/forum#39]
Olá. Sou mais um iniciante no Vue, e gostaria de ajuda para me dar um norte.

Estou criando um projeto pessoal, para aplicar o que aprendi em um curso de Vue.

Eu estou tentando fazer meu componente executar uma função, após alguma alteração feita direto na DOM.

Ex: Eu tenho um campo "Input text", e gostaria que quando o usuário fizesse alguma alteração nesse campo, executasse uma função do componente.
Atualmente eu só consigo fazer com que essa função seja executada, quando a alteração feita no campo input, seja uma alteração realizada através de outra função já executada pelo componente. Quando o usuário digita, ou altera direto no campo, a função não é executada.

O que eu estou usando no campo para disparar a ação é: "v-on:change='funcao()'".
Se por exemplo, eu crio um botão no componente, que chame uma função para escrever algo nesse campo, aí sim a função é executada, mas se o usuário direto fizer alguma alteração, a função não é chamada.

O que aprendi no Vue, é que ele cria uma DOM virtual. E executa e observa as alterações feitas na "DOM Virtual", e não direto na "DOM real".
É isso que estou entendo que está acontecendo, o Vue só "observa" as alterações feitas da DOM Virtual.

Mas o que fazer nesses casos, onde eu preciso que alguma ação seja tomada, se houver alteração direto na DOM Real? Usar Javascript puro? "document.getElementById()" etc?

Observação: O framework que eu usava antes era apenas o JQuery. Não sei se eu tenho q mudar muito minha mentalidade de programação, mas minha cabeça está acostumada a pensar em seletores etc.. rsrs.

**Comment by rodrigodjodi** [comment]
Amigo, começando pelo fim, tente dar um tempo dos seletores, no caso extremo de mexermos algo diretamente no DOM faremos isso com [refs](https://br.vuejs.org/v2/api/#ref).
Sempre coloque código, é mais fácil para ajudar e até para ler.
Vou colocar um código aqui que altera o texto quando o evento change é disparado, veja se lendo dele você consegue entender o que está faltando no seu caso:
``` HTML
<div id="app">
<!-- perceba que chamos a função pelo nome, sem executar diretamento com () -->
  <input type="text" v-model="inputText" v-on:change="capitalize"/>
  <p>O texto digitado é: {{inputText}}</p> 
  <p> (Tem que mudar a cada entrada do teclado)</p>
  <p>O texto digitado em CAPS é: {{capitalized}} </p>
  <p>(Muda apenas quando a função change atribuída ao evento change for executada)
</div>
```
``` JS
new Vue({
  el: "#app",
  name: "app",
  data:{
    inputText:"", // o parâmetro alterado pelo v-model, que reage a cada toque
    capitalized:"" // o parâmetro alterado pela função capitalize
  },
  methods: {
    capitalize(ev) {
      this.capitalized = ev.target.value.toUpperCase()
    }
  }
});
```

Aqui o [codepen ](https://codepen.io/djodi/pen/QWLXGOJ) do código acima. Esepro que ajude,

Rodrigo

**Comment by csrmds** [comment]
> 
> 
> Amigo, começando pelo fim, tente dar um tempo dos seletores, no caso extremo de mexermos algo diretamente no DOM faremos isso com [refs](https://br.vuejs.org/v2/api/#ref).
> Sempre coloque código, é mais fácil para ajudar e até para ler.
> Vou colocar um código aqui que altera o texto quando o evento change é disparado, veja se lendo dele você consegue entender o que está faltando no seu caso:
> 
> ```
> <div id="app">
> 
>   <input type="text" v-model="inputText" v-on:change="capitalize"/>
>   <p>O texto digitado é: {{inputText}}</p> 
>   <p> (Tem que mudar a cada entrada do teclado)</p>
>   <p>O texto digitado em CAPS é: {{capitalized}} </p>
>   <p>(Muda apenas quando a função change atribuída ao evento change for executada)
> </div>
> ```
> 
> ```js
> new Vue({
>   el: "#app",
>   name: "app",
>   data:{
>     inputText:"", // o parâmetro alterado pelo v-model, que reage a cada toque
>     capitalized:"" // o parâmetro alterado pela função capitalize
>   },
>   methods: {
>     capitalize(ev) {
>       this.capitalized = ev.target.value.toUpperCase()
>     }
>   }
> });
> ```
> 
> Aqui o [codepen ](https://codepen.io/djodi/pen/QWLXGOJ) do código acima. Esepro que ajude,
> 
> Rodrigo

Rodrigo.. muito grato pela ajuda!!

Utilizar o v-model resolveu minha questão!!

Não postei meu código aqui, pq já havia feito tanta bagunça e tanto teste.. que não ia dar pra entender nada.. mas enfim..
Vou tentar ver outros videos de projeto pratico do curso de Vue que iniciei.

Valeu Rodrigo!!
