### ISSUE TITLE
Login/Autenticação com Vuejs + vue-apollo + GraphQL

### ISSUE THREAD

**Issue by vandrepaulo** [vuejs-br/forum#40]
Olá, pessoal!

Sou novo na comunidade, estou iniciando os estudos e aplicando em um projeto importante para um cliente e me deparei com o primeiro desafio: Criar o login/autenticação da aplicação usando o **vue-apollo + GraphQl + Vuex**. Alguém já teve essa experiência de uso e gostaria de me dá um direcionamento? Não achei material em português sobre esse assunto.

Agradeço a todos que toparem esse desafio comigo. Pode até ser motivo de um post no blog oficial!

**Comment by VitorLuizC** [comment]
Já vou começar falando para repensar o uso do Vuex no projeto. Hoje o Apollo tem gerenciamento de estados local e facilita bastante usar uma única fonte de verdade no App.

Sobre a auntenticação em si, todas as vezes que fiz foi com JWT mesmo. Sem mistério, faz a requisição, salva o token no cookie ou storage e usa ele nos links do ApolloClient para mandar nos cabeçalhos.

**Comment by vandrepaulo** [comment]
Vitor, você teria algum material sobre a autenticação para que eu pudesse da uma olhada? Ou algum exemplo? Agradeço.

**Comment by kavalcante** [comment]
Fala @vandrepaulo, hoje trabalhamos exatamente dessa forma. No nosso caso, está estruturado da seguinte maneira:

- Nossa autenticação usa REST tradicional (nossa aplicação possui SSO com outras aplicações de clientes e afins, então utilizamos REST somente nessa parte).
- Ao se autenticar via REST ele retorna um objeto com o usuário e o token (utilizamos JWT)
- O próprio vue-apollo grava o cookie no navegador e gerencia ele internamente
- Eu gravo o usuário no vuex para consultas em todo o sistema
- Ao relogar a página, eu vou no backend e pergunto pra ele quem é usuário do token e se ele está válido, e gravo novamente no vuex.

Dessa forma funciona bem para nós e atendemos os requisitos de segurança que nossa aplicação necessita (como não gravar informações críticas no cliente, por exemplo)

**Comment by kavalcante** [comment]
Se você for fazer a autenticação dentro do próprio graphql, a regra não muda muito, a diferença é que você utilizaria uma query ou mutation (aí nesse caso, não sei qual seria o mais apropriado).

Aqui tem um tutorial do HowToGraphQL, pode ser que seja útil: https://www.howtographql.com/vue-apollo/5-authentication/

**Comment by vandrepaulo** [comment]
Olá, pessoal!
Primeiramente, obrigado a todos que me deram um direcionamento para resolver essa dúvida. Informo que consegui resolver, usei o GraphQL + ApolloClient + JWT. Valeu pela ajuda!
