### ISSUE TITLE
Primeiro projeto com Vue.js

### ISSUE THREAD

**Issue by miqueiasazevedo** [vuejs-br/forum#43]
Fala, galera!!

Sou novo por aqui e em basicamente tudo no Vue.js. Venho de uma pequena experiência no front end, trabalhando com HTML, CSS e JS (JQuery). Diria que tenho um conhecimento intermediário em JS.

Não tem muito tempo que estou nessa área, mas resolvi aprofundar de vez no desenvolvimento web como o que quero realmente fazer.

Aliado a isso surgiu uma proposta para o desenvolvimento de uma aplicação para o mapeamento de pontos turístico de uma cidade para a criação de rotas para visitantes com informações destes pontos , utilizando PHP no back (minha esposa é desenvolvedora) e a API do Google Maps.

Inicialmente a solicitação foi para uma aplicação nativa, mas já estou pesquisando a algum tempo sobre app web, pwa e etc... e, talvez com o meu pouco conhecimento do assunto, estou vendo a possibilidade de desenvolver a aplicação desta forma.

Pesquisando sobre as ferramentas necessárias para isso comecei a ouvir alguns podcasts, inclusive o vuejs-br, e desta forma cheguei até aqui.

Enfim, vamos as dúvidas. Gostaria de saber se:
- Em uma analise superficial do cenário, é possível utilizar o Vue.js para isso. 
- Tendo em vista minha "vasta" experiência, a minha curva de aprendizado para desenvolver algo desse tipo seria muito grande? Quanto?
- Qual o nível de conhecimento do Vue.js seria necessário para este projeto?

Desde já, muito obrigado a todos!

**Comment by SkyaTura** [comment]
A ideia do seu projeto é muito interessante, e o Google Maps já fornece grande parte dos dados que você precisa (inclusive alguns pontos turísticos já cadastrados no próprio maps).

Antes de responder seus questionamentos, eu acho importante ressaltar que, embora seja muito bem documentada e de fácil utilização, as APIs do Google Maps são pagas e a cota gratuita foram reduzidas a um tempo atrás.

Pela minha experiência com integrações do tipo, eu acho que antes de validar a tecnologia que você vai usar no seu código, seria interessante se vocês fizessem um levantamento do volume esperado de acessos e consultas ao sistema e o quanto isso pode custar mensalmente, para evitar frustrações após tempo e dinheiro serem investidos no projeto.

Dito isso, e considerando que esses pontos já foram solucionados, vou tentar responder as suas perguntas da maneira que faz mais sentido pra mim. Ok?

* **Em uma analise superficial do cenário, é possível utilizar o Vue.js para isso.**
* **Tendo em vista minha "vasta" experiência, a minha curva de aprendizado para desenvolver algo desse tipo seria muito grande? Quanto?**

É perfeitamente possível executar isso com Vue!

Talvez você tenha um pouco de dificuldade na integração com o Google Maps, pois embora já até existam componentes prontos para isso, eles são apenas uma camada de "abstração" da biblioteca oficial da Google. Sendo assim, a utilização desses componentes envolvem conceitos e características um pouco mais avançadas do que é visto por uma pessoa iniciante (principalmente se não houver pelo menos experiência com outras aplicações de JS).

Mas isso de forma alguma é um impeditivo no seu projeto, com o devido esforço você pode integrar as duas tecnologias, e mesmo se achar que essa integração ainda não está ao seu alcance, pode optar por usar o Vue para a estruturação do site e das outras páginas, e fazer a integração com o Maps usando JavaScript puro, afinal, ele ainda está lá.

* **Qual o nível de conhecimento do Vue.js seria necessário para este projeto?**

Eu acho muito complicado "mensurar" conhecimento, eu acho que o único requisito que existe para executar esse projeto é a dedicação mesmo, e o tempo depende muito do seu próprio ritmo.

Espero que isso ajude de alguma forma e que você tenha ótimas experiências com o Vue.js
Seja bem vindo a comunidade 😉

**Comment by miqueiasazevedo** [comment]
Muito obrigado @SkyaTura .
Ajudou muito. Suas dicas ajudarão bastante.

Ainda estou meio receoso por se tratar de um projeto não muito simples, mas gostaria de aproveitar esta oportunidade para aprender estas tecnologias pois acredito que isto agregará muito na experiência do usuário.

Provavelmente retornarei aqui mais algumas vezes pois terei muitas dúvida..rsrs.
Mas, escolhi o Vue principalmente pela comunidade e acredito que isso fará bastante diferença.

Mais uma vez, muito obrigado!
