### ISSUE TITLE
Sobrescrever estilo de componente externo

### ISSUE THREAD

**Issue by marcelcunha** [vuejs-br/forum#47]
Olá pessoal, estou criando minha primeira aplicação Vue (já havia brincando com tutoriais antes mas nunca executado um projeto), onde migrei um conteúdo criado em html e css para uma SPA que está consumindo uma API. Usando vue-cli criei o projeto já importando o vue-router, criei dois componentes um Footer e um Header além de 8 views. Toda parte de programação está ok, meu único problema foi com aplicação de css.
Todas minhas páginas com exceção da home possuem o mesmo estilo de css, portanto migrei e adaptei o estilo para a tag style do componente Header (removi o atributo scoped). Acreditava que se usasse scoped style no Home para sobrescrever as classes css de Header funcionaria, mas não. Então resolvi tirar e funcionou, mas todas outras views ficaram com o mesmo estilo. 
Já dei uma procurada e não encontrei algo que me ajudasse, até achei no stackoverflow alguém que passou pela mesma situação mas não teve uma resposta funcional. 

Se alguém tiver alguma dica por favor me responda. Muito obrigado.

**Comment by emanuelgsouza** [comment]
Fala! Então, se eu entendi bem, você possui 8 views com o mesmo estilo de Header e Footer, e apenas na Home este estilo muda. Correto? O que de fato muda neste estilo?

O atributo *scoped* na tag `<style>` faz com que na hora de gerar o HTML e o CSS, ambos terão um *hash* único, fazendo com que os estilos daquele componente em especial não sejam compartilhados com outros locais e o afetem.

Agora o porquê da minha pergunta anterior: quando usamos o atributo *scoped*, podemos acessar os seletores de componentes filhos através do `>>>` na definição de seletor CSS do nosso componente ([Deep Selector](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors)). Dá uma olhada, possa ser que te ajude

**Comment by simaodeveloper** [comment]
Não tem como passar uma classe de modificação via parametro?

**Comment by marcelcunha** [comment]
@emanuelgsouza Exato. Bastante coisa muda: altura do header; divs tem display none numa, noutra não; posicionamento do menu; disposição dos itens internos e cores. 
Imaginei que poderia fazer como num HTML e CSS comum, onde tendo um arquivo css com estilo pré existente se eu crio num novo, meu seletores vão sobrescrever a estilização primária. Me enganei bastante pelo visto. 
Vou dar uma olhada no link que mandou e ver se me ajuda. Muito obrigado.

**Comment by marcelcunha** [comment]
@simaodeveloper Na minha situação eu teria de "duplicar" e alterar pelo menos umas 15 classes. Acho que é contraproducente. Obrigado.

**Comment by emanuelgsouza** [comment]
Então. Pelo que você está comentando, eu creio que seria melhor criar um componente apenas para o `Header` do `Home`. Se é praticamente outro header, ele seria o `HomeHeader`, por exemplo.

Pelo que você comenta abaixo, eu não duplicaria tudo, eu teria um CSS comum geral para os headers e nos componentes, Header (usado pelas inúmeras views) e o HomeHeader (usado apenas pela Home), eu teria os estilos bem específicos.

Espero ter ajudado no debate

**Comment by simaodeveloper** [comment]
@marcelcunha sugeri passar uma classe por parametro, justamente para adicionar apenas uma classe modificadora no elemento ancestral ou elemento raiz do componente, assim, você estiliza os demais elementos a partir dele. 

Com a omissão da complexidade da sua arquitetura eu concordo com o caminho que o @emanuelgsouza propôs já que é um componente diferente dos demais.

**Comment by marcelcunha** [comment]
@emanuelgsouza Dado a minha pouca experiência e pouco prazo pra procurar, acredito que sua ideia seja a melhor solução no momento.

Muito obrigado a você ao @simaodeveloper pela ajuda.
