### ISSUE TITLE
Campo de busca em componente estilo DataTables

### ISSUE THREAD

**Issue by marcelcunha** [vuejs-br/forum#49]
Olá pessoal, comecei com Vue a pouco tempo e pra melhorar minha lida com o framework estou escrevendo alguns componentes que uso com frequência nele (imagino que já existam projetos bem desenvolvidos, documentados e testados mas meu intuito até então é aprender). 

Criei uma tabela dinâmica, passo um array com as colunas e outro com as linhas, que ordena crescente e decrescente quando clicado no título. Queria um campo de texto único que filtrasse os elementos da tabela como nesse vídeo bem antigo do: [Fábio Vedovelli](https://youtu.be/TGSJjDahlrQ?t=1960) (após o minuto 32). Esse vídeo é de 2016 e ele usou a primeira versão do Vue (filterBy) que aparentemente não funciona no Vue 2.

Fiz alguns testes usando o `array filter` do javascript, mas nesse caso teria de passar qual o atributo do objeto estaria procurando. Também testei usando `reduce` na callback do `array filter`, mas não obtive sucesso. 

Alguém pode me dar ideia de que caminho seguir? Muito obrigado.

**Comment by simaodev** [comment]
Opa @marcelcunha , tudo bem?
Cara agora é só fazendo filter usando o nativo do JS, isso da mais possibilidades.
Passe uma função retornando a lista filtrada a lista, coloque como parâmetro o campo do filtro e dentro da função vc deve fazer a logica do mesmo.

**Comment by marcelcunha** [comment]
Olá @wfsimao, obrigado pela sua resposta. Considerando que eu tenho apenas um campo de buscas, ao filtrar a lista de objetos consigo fazer isso apenas para um atributo desse objeto, certo?

**Comment by simaodev** [comment]
Você pode filtrar todos se quiser, basta aprimorar seu filter.
Um exemplo bem básico é percorrer todas as suas colunas(todos os atributos do objeto) e fazer um filter em cada um acumulando os resultados em um array q será retornardo

**Comment by marcelcunha** [comment]
@wfsimao Muito obrigado. Dando mais uma mexida, cheguei no seguinte código que até então resolve meu problema (pretendo dar uma melhorada no futuro): 

```javascript
 this.data.filter(row =>
        Object.entries(row).some(attribute => {
          return attribute
            .toString()
            .toLowerCase()
            .match(this.search);
        })
      );
```

Caso alguém tenha uma dúvida parecida, tem um ponto de partida pra sair.
