### ISSUE TITLE
Criar elementos dinamicamento V-FOR e nomea-los

### ISSUE THREAD

**Issue by wesleyribeiro123** [vuejs-br/forum#62]
Boa tarde pessoal

Estou iniciando meus estudos no Vue.JS e gostaria de umas dicas de como melhor proceder para um problema que estou enfrentando...
A problemática é teoricamente simples, a execução que está complicando, rsrs

Criei uma tela onde tenho uma "table" e dentro de cada célula desta tabela quero atribuir um "button", como vemos na imagem abaixo:

![image](https://user-images.githubusercontent.com/63206933/107885419-0376ad80-6ed9-11eb-8cca-a65b95296f8d.png)

Para criação destes elementos eu utilizei a seguinte estrutura:
```
    <div id="tela"> <!-- Tela do Projeto -->
      <table id="tab"> <!-- Tabela onde insiro os buttons -->
        <tr v-for="v in vert" :key="v" id="vert"> <!-- Laço que irá criar as células Verticais -->
          <td v-for="h in horiz" :key="h" id="horiz"> <!-- Laço que irá popular na Horizontal -->
            <button id="btn" @click.prevent="achei"> <!-- Button -->
              <p style="display: none"> <!-- display: none, ao ser clicado vou mudar a propriedade e tornar o icone visivel -->
                <i class="fas fa-eye"></i>
              </p>
            </button>
          </td>
        </tr>
      </table>
    </div>

<script>
...
  data: ()=>{
    return {
      vert: 19,
      horiz: 30,
    }
  },
...
</script>
```
A minha ideia inicial é esta, gerar uma tela estilo "campo minado" e ao receber um clique o icone ser exibido.

Não estou conseguindo identificar o "button" quando crio o methods: achei() atribuido ao evento @click

Se houver alguma outra forma mais prática ou até mesmo uma forma melhor de montagem da tela, estou aberto a sugestões, o intuito da criação deste projeto é puramente didático para reforçar o APRENDIZADO...

Desde já agradeço o espaço e a atenção de todos!!!

**Comment by devrrnogueira** [comment]
`<button @click="achei(h,v)"> <!-- Button -->`

```
methods: {
    achei(h,v) {
        console.log(h,v)
    }
}
```
se entendi a pergunta, isso resolve

**Comment by wesleyribeiro123** [comment]
> `<button @click="achei(h,v)"> <!-- Button -->`
> 
> ```
> methods: {
>     achei(h,v) {
>         console.log(h,v)
>     }
> }
> ```
> se entendi a pergunta, isso resolve

Brother resolveu meu problema, era exatamente oq precisava... Muito obrigado!!!

Preciso estudar mais sobre eventos, rsrs
