### ISSUE TITLE
Problema classes typescript com funções/propriedades privadas

### ISSUE THREAD

**Issue by SebastiaoAlterdata** [vuejs-br/forum#72]
Olá devs.

Estou com problema em uma situação com funções privadas, utilizando Vue x TS. No caso, quando utilizo essa classe como parâmetro de uma função ou tipada como prop de um componente, o ts fica gritando por esses caras privados. Ex:

```
class Test {
  a?: string;
  b?: string;

  constructor(test?: Partial<Test>) {
    this.a = 'testando';
    console.log(test);
  }

  private privateTest() {
    console.log('Meu teste');
  }

  privateTest2() {
    console.log('Meu teste 2');
  }
}

export default Test;
```
```
  const vueTest1 = (test: Test) => {
    console.log(test);
  };

  const vueTest2 = () => {
    vueTest1(myTest);
  };
```

Essa variável **myTest** é um reactive, que recebe o dado por api. 

![image](https://user-images.githubusercontent.com/130068005/233083938-0ed53da4-220c-4dcf-a236-74f2988de775.png)
![image](https://user-images.githubusercontent.com/130068005/233084166-90fb8d9e-15ab-4c89-a175-78e3a48bb5fb.png)

Esse caso só acontece se a classe possuir métodos ou propriedades private, protected.

Se alguém tiver uma ideia para me orientar sobre.
Valeu!!

**Comment by SkyaTura** [comment]
A função `vueTest1` recebe como parâmetro uma instância de `Teste`, porém, o resultado do helper `reactive` *não* possui o mesmo tipo de entrada:

> O objeto retornado e seus objetos aninhados estão envolvidos com [ES Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) e não são iguais aos objetos originais. É recomendável trabalhar exclusivamente com o proxy reativo e evitar depender do objeto original.
https://vuejs.org/api/reactivity-core.html#reactive

Uma forma simples de entender o resultado é imaginar que a função `reactive` é semelhante ao exemplo:
```typescript
const myTeste = { ...(new Test()) }
```
_Não é assim que funciona, isso é apenas para ilustração_

Sendo assim, não é possível ter acesso aos elementos privados da classe `Teste`, uma vez que eles não podem ser lidos externamente, e consequentemente, não podem ser escritos no novo objeto criado pelo `reactive`.

**Comment by SebastiaoAlterdata** [comment]
> A função `vueTest1` recebe como parâmetro uma instância de `Teste`, porém, o resultado do helper `reactive` _não_ possui o mesmo tipo de entrada:
> 
> > O objeto retornado e seus objetos aninhados estão envolvidos com [ES Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) e não são iguais aos objetos originais. É recomendável trabalhar exclusivamente com o proxy reativo e evitar depender do objeto original.
> > https://vuejs.org/api/reactivity-core.html#reactive
> 
> Uma forma simples de entender o resultado é imaginar que a função `reactive` é semelhante ao exemplo:
> 
> ```ts
> const myTeste = { ...(new Test()) }
> ```
> 
> _Não é assim que funciona, isso é apenas para ilustração_
> 
> Sendo assim, não é possível ter acesso aos elementos privados da classe `Teste`, uma vez que eles não podem ser lidos externamente, e consequentemente, não podem ser escritos no novo objeto criado pelo `reactive`.

Entendi. No caso, pelo que consegui ler um pouco sobre, seria a solução fazer um cast desse cara? Tipo reactive(new Test()) as Test;

**Comment by SkyaTura** [comment]
Essa solução proposta iria resolver o erro de compilação porque você iria enganar o Typescript, mas qualquer coisa que tente acessar os métodos privados irão falhar porque eles não existem no contexto do objeto reativo.

A solução definitiva é um pouco mais complexa, porque esse helper foi criado para ser usado com objetos simples.

O ideal seria refatoração da sua classe para deixá-la compatível com o seu caso de uso real ou então aplicar uma lógica personalizada para envolver sua instância com capacidades reativas

**Comment by SebastiaoAlterdata** [comment]
> Essa solução proposta iria resolver o erro de compilação porque você iria enganar o Typescript, mas qualquer coisa que tente acessar os métodos privados irão falhar porque eles não existem no contexto do objeto reativo.
> 
> A solução definitiva é um pouco mais complexa, porque esse helper foi criado para ser usado com objetos simples.
> 
> O ideal seria refatoração da sua classe para deixá-la compatível com o seu caso de uso real ou então aplicar uma lógica personalizada para envolver sua instância com capacidades reativas

Perfeito! Obrigado @SkyaTura pela explicação perante ao contexto.
